quarkus:
  devservices:
    enabled: false
  index-dependency:
    geo:
      group-id: it.lysz210.akasha.capacnan
      artifact-id: blueprint-geo
    credentials:
      group-id: it.lysz210.akasha.capacnan
      artifact-id: blueprint-credentials
  config:
    locations:
      - "blueprint-root.yaml"
      - "blueprint-geo.yaml"
      - "blueprint-credentials.yaml"
  http:
    port: 8000
nats:
  connection:
    url: "${CAPACNAN_SERVER_URI:nats://localhost:4222}"
