quarkus:
  devservices:
    enabled: false
  index-dependency:
    blueprint:
      group-id: it.lysz210.akasha.capacnan
  config:
    locations:
      - "blueprint.yaml"
      - "nats-geo.yaml"
      - "nats-security.yaml"
  http:
    port: 8000
  messaging:
    nats:
      connection:
        servers:
          - "${CAPACNAN_SERVER_URI:nats://localhost:4222}"
      streams:
        geo:
          name: "${capacnan.geo.stream}"
          configuration:
            subjects: ${capacnan.geo.subjects}