quarkus:
  messaging:
    nats:
      key-value-stores:
        security:
          storage-type: File
          bucket-name: "${capacnan.security.kv.bucket}"
      streams:
        security:
          name: "${capacnan.security.stream}"
          configuration:
            subjects: ${capacnan.security.subjects}
            storage-type: File
